- hosts: nginx
  tasks:
    - name: 'Installing nginx'
      apt:
        name: nginx
        state: latest
      become: yes	

    - name: 'Updating nginx config'
      template:
        src: pass.j2
        dest: /etc/nginx/sites-enabled/pass
      notify: reload nginx
      become: yes

    - name: 'Installing python'
      apt:
        name: python
        state: latest
      become: yes

    - name: 'Installing pip'
      apt:
        name: python-pip
        state: latest
      become: yes

    - name: 'Installing docker'
      apt:
        name: docker.io
        state: latest
      become: yes

    - name: 'Installing docker module for Python'
      pip:
        name: docker
      become: yes
      
    - name: 'Start or replace a container with docker_container module'
      docker_container:
        name: "gocalc"
        image: "vglushko/gocalc"
        detach: True
        labels:
          app: "web-container"
        env:
          test1: "es1234"
        ports:
          - '7000:7000'
      become: yes
      
 
  handlers:
  - name: reload nginx
    service:
      name: nginx
      state: reloaded
